function Compile(entree)
    entree = [[name:tmp;
%%
]] .. entree
    f = io.popen('echo "' .. entree .. '" | gregorio -sS', 'r')
    tex.sprint(f:read('*a')
		:gsub([[%% File generated by gregorio [^\n]+]], '')
		:gsub([[%% %a[^\n]+]], '')
		:gsub('%%\n', '')
		:gsub([[\endinput %%]], '')
    )
    f:close()
end
